name: entangle
description: entangle is use Websocket web-server in dartVM. And you can use entangle-clien in Flutter.
version: 0.0.1
author: pillar<pillar@gmail.com>
homepage: https://github.com/ymzuiku/dart-entangle

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:

dev_dependencies:
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
